WebApplication1/Models/ErrorViewModel.cs
using System;

namespace WebApplication1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebApplication1/Controllers/Home2Controller.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Controllers
{
    public class Home2Controller : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        // GET: /Home2Controller/test/
        public string Test()
        {
            return "Your are on the same Node tho ( •_•)";
        }
    }
}

WebApplication1/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Text.Encodings.Web;
using System.Net.Http;
using System.Net.Http.Headers;
using Newtonsoft.Json;
using System.Threading;


namespace WebApplication1.Controllers
{
    public class HomeController : Controller
    {
        private Random rnd;

        // GET: /HomeController/
        public IActionResult Index()
        {
            return View();
        }

        // GET: /HomeController/testsamenode/
        public async Task <string> TestSameNode()
        {
            using (HttpClient client = new HttpClient())
            {
                string url = "http://172.29.213.18:32000/home2/test"; //specify your ip of the masternode and the port of the node

                HttpResponseMessage response = await client.GetAsync(url);

                if (response.IsSuccessStatusCode)
                {
                    string data = await response.Content.ReadAsStringAsync();
                    
                    return data;
                }
                return "error";
            }
        }

        // GET: /HomeController/testanothernode/
        public async Task<string> TestAnotherNode()
        {
            using (HttpClient client = new HttpClient())
            {
                string url = "http://172.29.213.18:32001/nothome/test"; //specify your ip of the masternode and the port of the node 
                HttpResponseMessage response = await client.GetAsync(url);

                if (response.IsSuccessStatusCode)
                {
                    string data = await response.Content.ReadAsStringAsync();

                    rnd = new Random();
                    int timeToWait = rnd.Next(1, 10);
                    
                    while (true)
                    {                      
                        Thread.Sleep(timeToWait * 100); //wait between 0.1 and 1 sek

                        return data;
                    }
                }
                return "Error";
            }
        }

        //Parameter angabe in die URL
        // GET: /Home/ItWorks/?looptimes=...
        // Requires using System.Text.Encodings.Web;
        public IActionResult ItWorks(string message = "You are pretty cool! ( •_•)>⌐■-■", int loopTimes = 2)
        {
            ViewData["Message"] = message;
            ViewData["LoopTimes"] = loopTimes;
            
            if(loopTimes > 100) 
            {
                ViewData["LoopTimes"] = 1;
                ViewData["Message"] = "Oh you try to loop it over 100 times huh?";
            }

            return View();
        }
    }
}

WebApplication1/Controllers/NotHomeController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication1.Controllers
{
    public class NotHomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        // GET: /NotHomeController/test/
        public string Test()
        {
            return "Your are on the same Node tho ( •_•)";
        }
    }
}

WebApplication1/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Epic Website";
}
    <h2>Want this taco?</h2>
    <pre>
    {\__/}
    ( ●.●)
    ( >🌮
    </pre>
     

WebApplication1/Views/Home/ItWorks.cshtml
<ul>
    @for (int i = 0; i < (int)ViewData["LoopTimes"]; i++)
    {
        <li>@ViewData["Message"]</li>
    }
</ul>

WebApplication1/Views/Home2/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Epic Website";
}
<h2>Noo!! it's mine!</h2>
<pre>
    {\__/}
    ( ●_●)
    🌮<
    </pre>

WebApplication1/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - (⌐■_■)</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>     
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">Home</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="navbar-brand" asp-controller="Home2" asp-action="Index">Home2</a>
                        </li>
                        <li class="nav-item">
                            <a class="navbar-brand" asp-controller="Home" asp-action="ItWorks">Click me!</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>   
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/darkmode-js@1.5.7/lib/darkmode-js.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>